### PR TITLE
Downgrade to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/sbt/sbt/issues/7118

### CODE REVIEW

**Review by mkurz — APPROVED** [review]
LGTM

**Comment by Locke** [comment]
The produced binary from the latest run https://github.com/sbt/sbtn-dist/actions/runs/3841138944 can be executed on my local Debian 11 x86_64 :rocket:

**Comment by mkurz** [comment]
Just to confirm, the sbtn-aarch64-pc-linux artifact also works on my aarch64 Linux machine.

**Comment by eed3si9n** [comment]
Thanks for the confirmation. Kicking off a release build by creating https://github.com/sbt/sbtn-dist/releases/tag/v1.8.2

**Pull request merged**
